CREATE TABLE IF NOT EXISTS schema_migrations (version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (
 id uuid PRIMARY KEY, email text NOT NULL UNIQUE, name text NOT NULL, password_hash text NOT NULL,
 role text NOT NULL DEFAULT 'member' CHECK(role IN ('owner','member')),
 revision integer NOT NULL DEFAULT 0, eligibility_epoch integer NOT NULL DEFAULT 0,
 settings jsonb NOT NULL DEFAULT '{"mode":"mcp","timezone":"Asia/Taipei","dailyTokenLimit":50000}',
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, expires_at timestamptz NOT NULL, created_at timestamptz DEFAULT now());
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE signup_invites (token_hash text PRIMARY KEY, created_by uuid REFERENCES users ON DELETE CASCADE, expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE TABLE assets (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, name text NOT NULL, mime text NOT NULL, size bigint NOT NULL, sha256 text NOT NULL, storage_key text NOT NULL, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id));
CREATE TABLE sources (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, title text NOT NULL, kind text NOT NULL, content text NOT NULL DEFAULT '', asset_id uuid, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id), FOREIGN KEY(owner_id,asset_id) REFERENCES assets(owner_id,id));
CREATE TABLE facts (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, kind text NOT NULL, title text NOT NULL, content text NOT NULL, source_id uuid, confirmed boolean NOT NULL DEFAULT false, revoked_at timestamptz, valid_until timestamptz, revision integer NOT NULL, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id), FOREIGN KEY(owner_id,source_id) REFERENCES sources(owner_id,id));
CREATE TABLE career_revisions (owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, revision integer NOT NULL, facts jsonb NOT NULL, markdown text NOT NULL, created_at timestamptz DEFAULT now(), PRIMARY KEY(owner_id,revision));
CREATE TABLE jobs (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, provider text NOT NULL, external_id text NOT NULL, title text NOT NULL, company text NOT NULL, location text NOT NULL DEFAULT '', market text NOT NULL DEFAULT 'TW', url text NOT NULL DEFAULT '', description text NOT NULL, requirements jsonb NOT NULL DEFAULT '[]', metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), UNIQUE(owner_id,id), UNIQUE(owner_id,provider,external_id));
CREATE TABLE collections (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, name text NOT NULL, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id));
CREATE TABLE collection_jobs (owner_id uuid NOT NULL, collection_id uuid NOT NULL, job_id uuid NOT NULL, PRIMARY KEY(collection_id,job_id), FOREIGN KEY(owner_id,collection_id) REFERENCES collections(owner_id,id) ON DELETE CASCADE, FOREIGN KEY(owner_id,job_id) REFERENCES jobs(owner_id,id) ON DELETE CASCADE);
CREATE TABLE resumes (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, title text NOT NULL, language text NOT NULL, career_revision integer NOT NULL, job_id uuid, blocks jsonb NOT NULL, fact_ids uuid[] NOT NULL, approved_at timestamptz, parent_id uuid, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id), FOREIGN KEY(owner_id,job_id) REFERENCES jobs(owner_id,id), FOREIGN KEY(owner_id,parent_id) REFERENCES resumes(owner_id,id));
CREATE TABLE answers (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, question text NOT NULL, semantic_key text NOT NULL, country text NOT NULL, company text NOT NULL DEFAULT '', value text NOT NULL, unit text NOT NULL DEFAULT '', reusable boolean NOT NULL DEFAULT false, confirmed_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz, valid_until timestamptz, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id));
CREATE TABLE applications (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, job_id uuid NOT NULL, resume_id uuid, cycle integer NOT NULL DEFAULT 1, status text NOT NULL DEFAULT 'preparing', version integer NOT NULL DEFAULT 0, submitted_at timestamptz, origin text NOT NULL DEFAULT 'user', notes text NOT NULL DEFAULT '', created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id), UNIQUE(owner_id,job_id,cycle), FOREIGN KEY(owner_id,job_id) REFERENCES jobs(owner_id,id), FOREIGN KEY(owner_id,resume_id) REFERENCES resumes(owner_id,id));
CREATE INDEX applications_owner_date ON applications(owner_id,submitted_at DESC);
CREATE TABLE application_events (id uuid PRIMARY KEY, owner_id uuid NOT NULL, application_id uuid NOT NULL, type text NOT NULL, payload jsonb NOT NULL, source text NOT NULL CHECK(source IN ('user_reported','runner','sync')), occurred_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz DEFAULT now(), FOREIGN KEY(owner_id,application_id) REFERENCES applications(owner_id,id) ON DELETE CASCADE);
CREATE TABLE dossiers (id uuid PRIMARY KEY, owner_id uuid NOT NULL, application_id uuid NOT NULL, hash text NOT NULL, snapshot jsonb NOT NULL, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id), FOREIGN KEY(owner_id,application_id) REFERENCES applications(owner_id,id) ON DELETE CASCADE);
CREATE TABLE policies (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, name text NOT NULL, version integer NOT NULL DEFAULT 1, enabled boolean NOT NULL DEFAULT false, rules jsonb NOT NULL, epoch integer NOT NULL DEFAULT 1, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id));
CREATE TABLE authorizations (id uuid PRIMARY KEY, owner_id uuid NOT NULL, dossier_id uuid NOT NULL, policy_id uuid, policy_version integer, policy_epoch integer, recovery_epoch integer NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz, consumed_at timestamptz, FOREIGN KEY(owner_id,dossier_id) REFERENCES dossiers(owner_id,id) ON DELETE CASCADE, FOREIGN KEY(owner_id,policy_id) REFERENCES policies(owner_id,id) ON DELETE CASCADE);
CREATE TABLE submission_attempts (id uuid PRIMARY KEY, owner_id uuid NOT NULL, application_id uuid NOT NULL, dossier_id uuid NOT NULL, status text NOT NULL, evidence jsonb NOT NULL DEFAULT '{}', permit_at timestamptz, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), FOREIGN KEY(owner_id,application_id) REFERENCES applications(owner_id,id) ON DELETE CASCADE, FOREIGN KEY(owner_id,dossier_id) REFERENCES dossiers(owner_id,id) ON DELETE CASCADE);
CREATE UNIQUE INDEX one_active_attempt ON submission_attempts(application_id) WHERE status NOT IN ('failed_safe','cancelled');
CREATE TABLE interviews (id uuid PRIMARY KEY, owner_id uuid NOT NULL, application_id uuid NOT NULL, round text NOT NULL, status text NOT NULL CHECK(status IN ('invited','scheduled','completed','cancelled')), starts_at timestamptz, timezone text NOT NULL DEFAULT 'Asia/Taipei', notes text NOT NULL DEFAULT '', created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id), FOREIGN KEY(owner_id,application_id) REFERENCES applications(owner_id,id) ON DELETE CASCADE);
CREATE TABLE preparations (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, title text NOT NULL, notes text NOT NULL DEFAULT '', created_at timestamptz DEFAULT now());
CREATE TABLE interview_notes (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, application_id uuid, interview_id uuid, title text NOT NULL, content text NOT NULL, asset_id uuid, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id), FOREIGN KEY(owner_id,application_id) REFERENCES applications(owner_id,id) ON DELETE CASCADE, FOREIGN KEY(owner_id,interview_id) REFERENCES interviews(owner_id,id), FOREIGN KEY(owner_id,asset_id) REFERENCES assets(owner_id,id));
CREATE TABLE offers (id uuid PRIMARY KEY, owner_id uuid NOT NULL, application_id uuid NOT NULL, currency text NOT NULL, amount numeric(16,2), period text NOT NULL CHECK(period IN ('month','year','hour')), terms text NOT NULL DEFAULT '', deadline date, status text NOT NULL DEFAULT 'received' CHECK(status IN ('received','accepted','declined','expired','withdrawn')), revision integer NOT NULL DEFAULT 1, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,id), FOREIGN KEY(owner_id,application_id) REFERENCES applications(owner_id,id) ON DELETE CASCADE);
CREATE TABLE offer_revisions (offer_id uuid REFERENCES offers ON DELETE CASCADE, revision integer NOT NULL, snapshot jsonb NOT NULL, created_at timestamptz DEFAULT now(), PRIMARY KEY(offer_id,revision));
CREATE TABLE proposals (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, kind text NOT NULL, payload jsonb NOT NULL, state text NOT NULL DEFAULT 'pending', created_at timestamptz DEFAULT now());
CREATE TABLE tasks (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, kind text NOT NULL, status text NOT NULL DEFAULT 'queued', input jsonb NOT NULL, result jsonb, error text, attempts integer NOT NULL DEFAULT 0, lease_until timestamptz, lease_token uuid, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE INDEX tasks_queue ON tasks(status,created_at);
CREATE TABLE credentials (owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, provider text NOT NULL, encrypted text NOT NULL, last4 text NOT NULL, created_at timestamptz DEFAULT now(), PRIMARY KEY(owner_id,provider));
CREATE TABLE usage (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, task_id uuid, day date NOT NULL DEFAULT CURRENT_DATE, reserved_tokens integer NOT NULL, actual_tokens integer, state text NOT NULL, provider_request_id text, created_at timestamptz DEFAULT now(), UNIQUE(task_id));
CREATE TABLE connections (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, provider text NOT NULL, encrypted text NOT NULL, state text NOT NULL DEFAULT 'active', cursor text, last_synced_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}', UNIQUE(owner_id,provider));
CREATE TABLE sync_evidence (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, provider text NOT NULL, external_id text NOT NULL, payload jsonb NOT NULL, created_at timestamptz DEFAULT now(), UNIQUE(owner_id,provider,external_id));
CREATE TABLE groups (id uuid PRIMARY KEY, name text NOT NULL, created_by uuid REFERENCES users ON DELETE SET NULL, created_at timestamptz DEFAULT now());
CREATE TABLE memberships (group_id uuid NOT NULL REFERENCES groups ON DELETE CASCADE, user_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, role text NOT NULL CHECK(role IN ('owner','admin','member')), share_status boolean NOT NULL DEFAULT false, created_at timestamptz DEFAULT now(), PRIMARY KEY(group_id,user_id));
CREATE TABLE group_invites (token_hash text PRIMARY KEY, group_id uuid NOT NULL REFERENCES groups ON DELETE CASCADE, expires_at timestamptz NOT NULL, used_at timestamptz, revoked_at timestamptz);
CREATE TABLE group_jobs (id uuid PRIMARY KEY, group_id uuid NOT NULL REFERENCES groups ON DELETE CASCADE, author_id uuid REFERENCES users ON DELETE SET NULL, job_key text NOT NULL, snapshot jsonb NOT NULL, created_at timestamptz DEFAULT now(), UNIQUE(group_id,job_key));
CREATE TABLE group_comments (id uuid PRIMARY KEY, group_id uuid NOT NULL REFERENCES groups ON DELETE CASCADE, author_id uuid REFERENCES users ON DELETE SET NULL, body text NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE note_shares (id uuid PRIMARY KEY, group_id uuid NOT NULL REFERENCES groups ON DELETE CASCADE, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, note_id uuid NOT NULL, snapshot jsonb NOT NULL, created_at timestamptz DEFAULT now(), FOREIGN KEY(owner_id,note_id) REFERENCES interview_notes(owner_id,id) ON DELETE CASCADE);
CREATE TABLE career_plans (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, title text NOT NULL, career_revision integer NOT NULL, sample jsonb NOT NULL, content jsonb NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE growth_tasks (id uuid PRIMARY KEY, owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, plan_id uuid REFERENCES career_plans ON DELETE CASCADE, title text NOT NULL, output text NOT NULL, completed_at timestamptz, evidence text NOT NULL DEFAULT '', created_at timestamptz DEFAULT now());
CREATE TABLE audit_events (id bigserial PRIMARY KEY, owner_id uuid REFERENCES users ON DELETE CASCADE, action text NOT NULL, resource_id text, created_at timestamptz DEFAULT now());
CREATE TABLE idempotency (owner_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, operation text NOT NULL, key text NOT NULL, request_hash text NOT NULL, result jsonb NOT NULL, created_at timestamptz DEFAULT now(), PRIMARY KEY(owner_id,operation,key));
CREATE TABLE auth_throttles (key text PRIMARY KEY, count integer NOT NULL DEFAULT 1, expires_at timestamptz NOT NULL);
CREATE TABLE oauth_clients (id text PRIMARY KEY, metadata jsonb NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE oauth_requests (id text PRIMARY KEY, client_id text NOT NULL REFERENCES oauth_clients ON DELETE CASCADE, params jsonb NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE oauth_codes (hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, client_id text NOT NULL REFERENCES oauth_clients ON DELETE CASCADE, redirect_uri text NOT NULL, challenge text NOT NULL, scopes text[] NOT NULL, resource text NOT NULL, expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE TABLE oauth_tokens (hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users ON DELETE CASCADE, client_id text NOT NULL REFERENCES oauth_clients ON DELETE CASCADE, scopes text[] NOT NULL, resource text NOT NULL, expires_at timestamptz NOT NULL, kind text NOT NULL CHECK(kind IN ('access','refresh')), grant_id uuid NOT NULL, revoked_at timestamptz);
CREATE INDEX oauth_grants ON oauth_tokens(user_id,grant_id);
